import Head from "next/head";
import { css } from "@emotion/react";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Popular Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={main}>{children}</main>
    </div>
  );
}

const main = css`
  color: red;
`;
