import Head from "next/head";
import { css } from "@emotion/react";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Popular Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={main}>{children}</main>
    </div>
  );
}

const main = css`
  width: 100%;
  max-width: 1200px;
  margin-right: auto;
  margin-left: auto;
  padding: 3rem 1rem;
`;
